name: Discord Notification

on:
  pull_request:
    types: [opened]

jobs:
  send_discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: distributhor/webhook-action@v2
        with:
          url: ${{ https://discord.com/api/webhooks/1235397882849267762/qbRGlEhNFCcnJjUxDzyPjrh4BgOAszWxppF117mBscuzRaQdhvHUmlFVMzvvqfhsyvCS}}
          content: "Um novo Pull Request foi criado "
